### ISSUE TITLE
编译时报错error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by lovebair2022** [LyleMi/aflnw#2]
![图片](https://user-images.githubusercontent.com/17331338/121802729-7d912600-cc70-11eb-9056-f7ee74031a3a.png)

**Comment by LyleMi** [comment]
你好，我没有成功复现这个错误，我使用的编译器版本是 afl-clang-fast++2.65d ，你可以尝试使用这个版本的 afl-clang 或检查代码是否与当前仓库保持同步。
