### ISSUE TITLE
采集种子输入的时候，最后的格式是什么样子的？

### ISSUE THREAD

**Issue by lovebair2022** [LyleMi/aflnw#3]
![图片](https://user-images.githubusercontent.com/17331338/121836529-348bb100-cd06-11eb-9f3e-35e3ee0abe2a.png)
wireshark抓包并没有抓到什么数据

**Comment by LyleMi** [comment]
aflnw只是对输入做了转发，其他的参数和afl等同，可以使用afl的参数指定输入或使用afl++的custom mutator对指定协议进行测试

**Comment by lovebair2022** [comment]
测试了下，似乎只能对TCP有作用，但是TCP是没有效果的。

**Comment by lovebair2022** [comment]
> 
> 
> aflnw只是对输入做了转发，其他的参数和afl等同，可以使用afl的参数指定输入或使用afl++的custom mutator对指定协议进行测试
测试了下，似乎只能对TCP有作用，但是TCP是没有效果的。
