### ISSUE TITLE
最新版本的代码如何使用？

### ISSUE THREAD

**Issue by zzyyrr** [LyleMi/aflnw#4]
你好，我注意到aflnw的代码有了更新，参数也更多了，请问有相关的文档说明如何使用吗？谢谢！

**Comment by LyleMi** [comment]
你好，已经对应更新了文档。之前的更新主要是进行了一些使用上的优化，包括提供了重定向标准输入输出流、调整测试环境、debug等选项，由于工作原因，在开源项目的维护上精力会有所不足，bug修复、issue回应等会不够及时，还请见谅。
