### ISSUE TITLE
在make时候遇到点问题

### ISSUE THREAD

**Issue by CyberHierarach** [LyleMi/aflnw#6]
~/aflnw/build$ make
[ 25%] Building C object CMakeFiles/aflnw.dir/src/afl.c.o
afl-cc++4.10c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
SanitizerCoveragePCGUARD++4.10c
[+] Instrumented 3 locations with no collisions (non-hardened mode) of which are 0 handled and 0 unhandled selects.
[ 50%] Building C object CMakeFiles/aflnw.dir/src/main.c.o
afl-cc++4.10c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
SanitizerCoveragePCGUARD++4.10c
[+] Instrumented 11 locations with no collisions (non-hardened mode) of which are 0 handled and 0 unhandled selects.
[ 75%] Building C object CMakeFiles/aflnw.dir/src/utils.c.o
afl-cc++4.10c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
SanitizerCoveragePCGUARD++4.10c
[+] Instrumented 114 locations with no collisions (non-hardened mode) of which are 0 handled and 0 unhandled selects.
[100%] Linking C executable aflnw
afl-cc++4.10c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
CMakeFiles/aflnw.dir/src/main.c.o:(.bss+0x0): multiple definition of `conf'; /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x22
CMakeFiles/aflnw.dir/src/afl.c.o:(.bss+0x0): first defined here
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
CMakeFiles/aflnw.dir/src/utils.c.o:(.bss+0x0): multiple definition of `conf'; CMakeFiles/aflnw.dir/src/afl.c.o:(.bss+0x0): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/aflnw.dir/build.make:129：aflnw] 错误 1
make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/aflnw.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2

**Comment by LyleMi** [comment]
This issue was caused by a change in the compiler's behavior. Please refer to [this](https://stackoverflow.com/questions/69908418/multiple-definition-of-first-defined-here-on-gcc-10-2-1-but-not-gcc-8-3-0) for more information.

Fix it with this [commit](https://github.com/LyleMi/aflnw/commit/7f4989d292d3e103dd978d795f81a3f8ee6f03ed) now

**Comment by CyberHierarach** [comment]
感谢您的回复和解决方案！问题已经得到解决
